name: report
url: https://github.com/tiaanduplessis/hexo-theme-brewski

menu:
  主页: /
  关于: /about
  归档: /archives
  留言: /comment
  订阅: /atom.xml

favicon: /favicon.svg
logo: /logo.svg

# Disqus shortname
disqus:

# Analytics
google_analytics:

# Copyright Infomation
copyright:
  since:
  name:
  url:
