name: report
url: https://github.com/tiaanduplessis/hexo-theme-brewski

menu:
  主页: /
  关于: /about
  归档: /archives
  留言: /comment
  订阅: /atom.xml

favicon: /favicon.svg
logo: /logo.svg

# Copyright Infomation
copyright:
  since: 2021
  name: Ray
  url: https://blog.reilkay.com
