name: report
url: https://github.com/Reilkay/hexo-theme-report

menu:
  主页: /
  归档: /archives/
  留言: /comment/
  关于: /about/
  订阅: /atom.xml

favicon: /favicon.svg
logo: /logo.svg

# Google Analytics
google_analytics:
  enable: true
  code: G-BLKG2GLF9E

# Copyright Infomation
copyright:
  since: 2021
  name: Ray
  url: https://blog.reilkay.com
